version: '2'
services:
    utchipster-app:
        image: utchipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://utchipster-postgresql:5432/utcHipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    utchipster-postgresql:
        extends:
            file: postgresql.yml
            service: utchipster-postgresql
