version: '2'
services:
    utchipster-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/utcHipster/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=utcHipster
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
